//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminMaintenance.AdminReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminReference.IWCFAdminMaintenance")]
    public interface IWCFAdminMaintenance {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAdminMaintenance/Login", ReplyAction="http://tempuri.org/IWCFAdminMaintenance/LoginResponse")]
        bool Login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAdminMaintenance/Login", ReplyAction="http://tempuri.org/IWCFAdminMaintenance/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string name, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFAdminMaintenanceChannel : AdminMaintenance.AdminReference.IWCFAdminMaintenance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAdminMaintenanceClient : System.ServiceModel.ClientBase<AdminMaintenance.AdminReference.IWCFAdminMaintenance>, AdminMaintenance.AdminReference.IWCFAdminMaintenance {
        
        public WCFAdminMaintenanceClient() {
        }
        
        public WCFAdminMaintenanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAdminMaintenanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAdminMaintenanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAdminMaintenanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string name, string password) {
            return base.Channel.Login(name, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string name, string password) {
            return base.Channel.LoginAsync(name, password);
        }
    }
}
